Change inputs and validate them.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -1,5 +1,8 @@
 # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
 # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
+
+name: R-CMD-check
+
 on:
   push:
   pull_request:
@@ -8,43 +11,127 @@ on:
   workflow_dispatch:
     # When running manually, allow users to customize the run:
     inputs:
+      # What options should be passed to "R CMD check"?
       check-manual:
-        description: 'check the manual'
+        description: 'Check the manual (yes/no)'
         required: false
-        default: 'true'
+        default: 'no'
       check-vignettes:
-        description: 'check the vignettes'
+        description: 'Check the vignettes (yes/no)'
         required: false
-        default: 'true'
+        default: 'no'
       run-tests:
-        description: 'run the tests'
+        description: 'Run the tests (yes/no)'
         required: false
-        default: 'true'
+        default: 'yes'
       check-examples:
-        description: 'check the examples'
+        description: 'Check the examples (yes/no)'
         required: false
-        default: 'true'
-      check-windows:
-        description: 'Test build on Windows'
-        required: false
-        default: 'false'
-      check-mac:
-        description: 'Test build on MacOS'
-        required: false
-        default: 'false'
-      check-r-release-version-on-ubuntu:
-        description: 'Check on Ubuntu using the release version of R'
-        required: false
-        default: 'false'
-      check-r-devel-version-on-ubuntu:
-        description: 'Check on Ubuntu using the development version of R'
-        required: false
-        default: 'false'
+        default: 'yes'
 
-name: R-CMD-check
+      # Which platforms should we test?
+      check-windows:
+        description: 'Test build on Windows (yes/no)'
+        required: false
+        default: 'no'
+      check-mac:
+        description: 'Test build on MacOS (yes/no)'
+        required: false
+        default: 'no'
+      check-r-release-version-on-ubuntu:
+        description: 'Test build on Ubuntu using the release version of R (yes/no)'
+        required: false
+        default: 'yes'
+      check-r-devel-version-on-ubuntu:
+        description: 'Test build on Ubuntu using the development version of R (yes/no)'
+        required: false
+        default: 'no'
+
+env:
+  # Note that checks against these values will all be case
+  # insensitive!  (Yes, these are interdependent, but it was too
+  # complicated to compute some values from others.)
+  valid-input-values: '[ "yes", "y", "no", "n" ]'
+  yes-values: '[ "yes", "y" ]'
+  no-values: '[ "no", "n" ]'
 
 jobs:
+  get_configuration:
+    name: Get run configuration
+    runs-on: ubuntu-latest
+    outputs:
+      # These are essentially validated, booleanized versions of the input parameters.
+      check-manual: ${{ steps.set_outputs.outputs.check-manual }}    
+      check-vignettes: ${{ steps.set_outputs.outputs.check-vignettes }}
+      run-tests: ${{ steps.set_outputs.outputs.run-tests }}    
+      check-examples: ${{ steps.set_outputs.outputs.check-examples }}
+      check-windows: ${{ steps.set_outputs.outputs.check-windows }}
+      check-mac: ${{ steps.set_outputs.outputs.check-mac }}    
+      check-r-release-version-on-ubuntu: ${{ steps.set_outputs.outputs.check-r-release-version-on-ubuntu }}    
+      check-r-devel-version-on-ubuntu: ${{ steps.set_outputs.outputs.check-r-devel-version-on-ubuntu }}
+    steps:
+      - name: Validate Input
+        run: |
+          echo "ALL_INPUTS_VALID=${{
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-manual) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-vignettes) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.run-tests) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-examples) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-windows) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-mac) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-r-release-version-on-ubuntu) &&
+            contains(fromJSON(env.valid-input-values), github.event.inputs.check-r-devel-version-on-ubuntu)
+          }}" >> $GITHUB_ENV
+      ## - name: Debug validity check
+      ##   run: |
+      ##     echo "${{ github.event_name }}"
+      ##     echo "${{ github.event_name == 'workflow_dispatch' }}"
+      ##     echo "${{  env.ALL_INPUTS_VALID }}"
+      ##     echo "${{  env.ALL_INPUTS_VALID == 'false' }}"
+      - name: Abort if invalid
+        if: github.event_name == 'workflow_dispatch' && env.ALL_INPUTS_VALID == 'false'
+        run: |
+          echo "::error::All inputs must be either 'yes', 'y', 'no', or 'n'."
+          exit 1 # Stop the workflow if bad input was given.
+
+      - name: Set configuration variables
+        # This is only for manual dispatches.
+        if: github.event_name == 'workflow_dispatch'
+        id: set_outputs
+        run: |
+          echo "::set-output name=check-manual::${{ contains(fromJSON(env.yes-values),
+                                                             github.event.inputs.check-manual) }}"
+          echo "::set-output name=check-vignettes::${{ contains(fromJSON(env.yes-values),
+                                                                github.event.inputs.check-vignettes) }}"
+          echo "::set-output name=run-tests::${{ contains(fromJSON(env.yes-values),
+                                                          github.event.inputs.run-tests) }}"
+          echo "::set-output name=check-examples::${{ contains(fromJSON(env.yes-values),
+                                                               github.event.inputs.check-examples) }}"
+          echo "::set-output name=check-windows::${{ contains(fromJSON(env.yes-values),
+                                                              github.event.inputs.check-windows) }}"
+          echo "::set-output name=check-mac::${{ contains(fromJSON(env.yes-values),
+                                                          github.event.inputs.check-mac) }}"
+          echo "::set-output name=check-r-release-version-on-ubuntu::${{
+                    contains(fromJSON(env.yes-values),
+                             github.event.inputs.check-r-release-version-on-ubuntu) }}"
+          echo "::set-output name=check-r-devel-version-on-ubuntu::${{
+                    contains(fromJSON(env.yes-values),
+                             github.event.inputs.check-r-devel-version-on-ubuntu) }}"
+
+  ## debug:
+  ##   name: Debug
+  ##   needs: get_configuration
+  ##   runs-on: ubuntu-latest
+  ##   steps:
+  ##     - run: |
+  ##         echo "${{ needs.get_configuration.outputs.check-windows }}"
+  ##         echo "${{ needs.get_configuration.outputs.check-mac }}"
+  ##         echo "${{ needs.get_configuration.outputs.check-r-release-version-on-ubuntu }}"
+  ##         echo "${{ needs.get_configuration.outputs.check-r-devel-version-on-ubuntu }}"
+
   matrix_prep:
+    name: Prepare strategy matrix
+    needs: get_configuration
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -55,32 +142,40 @@ jobs:
         uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
         with:
           inputFile: '.github/workflows/matrix_includes_for_R-CMD-check.json'
+
+          # This filter uses the JMESPath query language to modify the
+          # strategy matrix.  See https://jmespath.org/.
           filter:
             '[?contains(runOnEvent, `${{ github.event_name }}`)
-               || (contains(os, `"windows"`) && `${{ github.event.inputs.check-windows }}` == `true`)
-               || (contains(os, `"macOS"`) && `${{ github.event.inputs.check-mac }}` == `true`)
+               || (contains(os, `"windows"`)
+                   && `${{ needs.get_configuration.outputs.check-windows }}`)
+               || (contains(os, `"macOS"`)
+                   && `${{ needs.get_configuration.outputs.check-mac }}`)
                || (contains(os, `"ubuntu"`)
-                   && ((contains(r, `"release"`) && `${{ github.event.inputs.check-r-release-version-on-ubuntu }}` == `true`)
-                       || (contains(r, `"devel"`) && `${{ github.event.inputs.check-r-devel-version-on-ubuntu }}` == `true`)))]'
+                   && ((contains(r, `"release"`)
+                        && `${{ needs.get_configuration.outputs.check-r-release-version-on-ubuntu }}`)
+                       || (contains(r, `"devel"`)
+                           && `${{ needs.get_configuration.outputs.check-r-devel-version-on-ubuntu }}`)))]'
 
-  # For debugging:
-  display_matrix:
-    needs: matrix_prep
-    runs-on: ubuntu-latest
-    steps:
-    - name: Report Configuration
-      env:
-        MATRIX_CONTEXT: ${{ needs.matrix_prep.outputs.matrix }}
-      run: |
-        echo "matrix: $MATRIX_CONTEXT"
+  ## # For debugging:
+  ## display_matrix:
+  ##   name: Display strategy matrix
+  ##   needs: matrix_prep # Supplies matrix output.
+  ##   runs-on: ubuntu-latest
+  ##   steps:
+  ##   - name: Report Configuration
+  ##     env:
+  ##       MATRIX_CONTEXT: ${{ needs.matrix_prep.outputs.matrix }}
+  ##     run: |
+  ##       echo "matrix: $MATRIX_CONTEXT"
 
   R-CMD-check:
-    name: ${{ matrix.os }} (${{ matrix.r }})
-    needs: matrix_prep
+    name: Check R package on platform ${{ matrix.os }} using the ${{ matrix.r }} version of R
+    needs: [get_configuration, matrix_prep]
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
-      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
+      matrix: ${{ fromJSON(needs.matrix_prep.outputs.matrix) }}
     env:
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true # affects behavior of the "remotes" package's install commands
       RSPM: ${{ matrix.rspm }}
@@ -153,7 +248,17 @@ jobs:
         ##   tinytex::tlmgr_install(c('siunitx', 'babel-english'))
         ## shell: Rscript {0}
 
-      - name: Maybe install TinyTex
+      ## - name: Debug TinyTex test
+      ##   run: |
+      ##     echo "${{ github.event_name }}"
+      ##     echo "${{ github.event_name != 'workflow_dispatch' }}"
+      ##     echo "${{ needs.get_configuration.outputs.check-vignettes }}"
+      ##     echo "${{ needs.get_configuration.outputs.check-manual }}"
+      ##     echo "${{ github.event_name != 'workflow_dispatch' ||
+      ##           needs.get_configuration.outputs.check-vignettes == 'true' ||
+      ##           needs.get_configuration.outputs.check-manual == 'true' }}"
+
+      - name: Check need for TinyTex
 
         # TinyTex must be installed iff we are checking either the
         # manual or the vignettes.  We always build and check the
@@ -163,14 +268,22 @@ jobs:
         # to install TinyTex only if user specified either the "check
         # the manual" or "check the vignettes".
 
-        if: ${{github.event_name != 'workflow_dispatch' ||
-               github.event.inputs.check-vignettes == 'true' ||
-               github.event.inputs.check-manual == 'true'}}
+        # Note: The second and third disjuncts in this "if" value are
+        # alternative ways of getting a boolean value from the outputs
+        # (which are strings):
+        run: |
+          echo "NEED_TINYTEX=${{
+            github.event_name != 'workflow_dispatch'
+            || needs.get_configuration.outputs.check-vignettes == 'true'
+            || fromJSON(needs.get_configuration.outputs.check-manual)
+          }}" >> $GITHUB_ENV  
+
+      - name: Install TinyTex
+        if: env.NEED_TINYTEX == 'true'
         uses: r-lib/actions/setup-tinytex@v1               
 
-      - if: ${{github.event_name != 'workflow_dispatch' ||
-               github.event.inputs.check-vignettes == 'true' ||
-               github.event.inputs.check-manual == 'true'}}
+      - name: Install extra LaTeX packages
+        if: env.NEED_TINYTEX == 'true' 
         run: |
           # Install a few LaTeX packages needed by the vignette not included
           # in tinytex:
@@ -184,18 +297,18 @@ jobs:
           if ('${{ github.event_name }}' == 'workflow_dispatch') {
             build_args_value <- c()
             args_value <- c('--as-cran')
-            if (as.logical('${{ github.event.inputs.check-manual }}') == FALSE) {
+            if ('${{ needs.get_configuration.outputs.check-manual }}' == 'false') {
               build_args_value <- append(build_args_value, '--no-manual')
               args_value <- append(args_value, '--no-manual')
             }
-            if (as.logical('${{ github.event.inputs.check-vignettes }}') == FALSE) {
+            if ('${{ needs.get_configuration.outputs.check-vignettes }}' == 'false') {
               build_args_value <- append(build_args_value, '--no-build-vignettes')
               args_value <- append(args_value, '--ignore-vignettes')
             }
-            if (as.logical('${{ github.event.inputs.run-tests }}') == FALSE) {
+            if ('${{ needs.get_configuration.outputs.run-tests }}' == 'false') {
               args_value <- append(args_value, '--no-tests')
             }
-            if (as.logical('${{ github.event.inputs.check-examples }}') == FALSE) {
+            if ('${{ needs.get_configuration.outputs.check-examples }}' == 'false') {
               args_value <- append(args_value, '--no-examples')
             }
           } else {
